- name: create jenkins jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "ci-pipelines" }
      - { folder_name: "infra-jobs" }
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/sravanreddy28/cart", folder_name: "ci-pipelines"}
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/sravanreddy28/roboshop-terraform", folder_name: "infra-jobs"}